const dataListCountries=`<option value = '​ Afghanistan--af' ></option>
<option value = '​ Aland Islands--ax' ></option>
<option value = '​ Ägypten--eg' ></option>
<option value = '​ Albanien--al' ></option>
<option value = '​ Algerien--dz' ></option>
<option value = '​ Andorra--ad' ></option>
<option value = '​ Angola--ao' ></option>
<option value = '​ Anguilla--ai' ></option>
<option value = '​ Antarktis--aq' ></option>
<option value = '​ Antigua und Barbuda--ag' ></option>
<option value = '​ Äquatorial Guinea--gq' ></option>
<option value = '​ Argentinien--ar' ></option>
<option value = '​ Armenien--am' ></option>
<option value = '​ Aserbaidschan--az' ></option>
<option value = '​ Äthiopien--et' ></option>
<option value = '​ Australien--au' ></option>
<option value = '​ Bahamas--bs' ></option>
<option value = '​ Bahrain--bh' ></option>
<option value = '​ Bangladesh--bd' ></option>
<option value = '​ Barbados--bb' ></option>
<option value = '​ Belgien--be' ></option>
<option value = '​ Saint-Barthelemy--bl' ></option>
<option value = '​ Bonaire--bq' ></option>
<option value = '​ Belize--bz' ></option>
<option value = '​ Benin--bj' ></option>
<option value = '​ Bermudas--bm' ></option>
<option value = '​ Bhutan--bt' ></option>
<option value = '​ Birma--mm' ></option>
<option value = '​ Bolivien--bo' ></option>
<option value = '​ Bosnien-Herzegowina--ba' ></option>
<option value = '​ Botswana--bw' ></option>
<option value = '​ Bouvet Inseln--bv' ></option>
<option value = '​ Brasilien--br' ></option>
<option value = '​ Britisch-Indischer Ozean--io' ></option>
<option value = '​ Brunei--bn' ></option>
<option value = '​ Bulgarien--bg' ></option>
<option value = '​ Burkina Faso--bf' ></option>
<option value = '​ Burundi--bi' ></option>
<option value = '​ Chile--cl' ></option>
<option value = '​ China--cn' ></option>
<option value = '​ Christmas Island--cx' ></option>
<option value = '​ Cook Inseln--ck' ></option>
<option value = '​ Costa Rica--cr' ></option>
<option value = '​ Dänemark--dk' ></option>
<option value = '​ Deutschland--de' ></option>
<option value = '​ Djibuti--dj' ></option>
<option value = '​ Dominika--dm' ></option>
<option value = '​ Dominikanische Republik--do' ></option>
<option value = '​ Ecuador--ec' ></option>
<option value = '​ El Salvador--sv' ></option>
<option value = '​ Elfenbeinküste--ci' ></option>
<option value = '​ Eritrea--er' ></option>
<option value = '​ Estland--ee' ></option>
<option value = '​ Falkland Inseln--fk' ></option>
<option value = '​ Färöer Inseln--fo' ></option>
<option value = '​ Fidschi--fj' ></option>
<option value = '​ Jersey--je' ></option>
<option value = '​ Finnland--fi' ></option>
<option value = '​ Frankreich--fr' ></option>
<option value = '​ Französisch Guyana--gf' ></option>
<option value = '​ Französisch Polynesien--pf' ></option>
<option value = '​ Französisches Süd-Territorium--tf' ></option>
<option value = '​ Gabun--ga' ></option>
<option value = '​ Gambia--gm' ></option>
<option value = '​ Georgien--ge' ></option>
<option value = '​ Ghana--gh' ></option>
<option value = '​ Gibraltar--gi' ></option>
<option value = '​ Grenada--gd' ></option>
<option value = '​ Griechenland--gr' ></option>
<option value = '​ Grönland--gl' ></option>
<option value = '​ Großbritannien--gb' ></option>
<option value = '​ Guernsey --gg' ></option>
<option value = '​ Guadeloupe--gp' ></option>
<option value = '​ Guam--gu' ></option>
<option value = '​ Guatemala--gt' ></option>
<option value = '​ Guinea--gn' ></option>
<option value = '​ Guinea Bissau--gw' ></option>
<option value = '​ Guyana--gy' ></option>
<option value = '​ Haiti--ht' ></option>
<option value = '​ Heard und McDonald Islands--hm' ></option>
<option value = '​ Honduras--hn' ></option>
<option value = '​ Hong Kong--hk' ></option>
<option value = '​ Indien--in' ></option>
<option value = '​ Indonesien--id' ></option>
<option value = '​ Irak--iq' ></option>
<option value = '​ Iran--ir' ></option>
<option value = '​ Irland--ie' ></option>
<option value = '​ Island--is' ></option>
<option value = '​ Israel--il' ></option>
<option value = '​ Italien--it' ></option>
<option value = '​ Jamaika--jm' ></option>
<option value = '​ Japan--jp' ></option>
<option value = '​ Jemen--ye' ></option>
<option value = '​ Jordanien--jo' ></option>
<option value = '​ Jugoslawien--yu' ></option>
<option value = '​ Kaiman Inseln--ky' ></option>
<option value = '​ Kambodscha--kh' ></option>
<option value = '​ Kamerun--cm' ></option>
<option value = '​ Kanada--ca' ></option>
<option value = '​ Kap Verde--cv' ></option>
<option value = '​ Kasachstan--kz' ></option>
<option value = '​ Isle of Man--im' ></option>
<option value = '​ Kenia--ke' ></option>
<option value = '​ Kirgisistan--kg' ></option>
<option value = '​ Kiribati--ki' ></option>
<option value = '​ Kokosinseln--cc' ></option>
<option value = '​ Kolumbien--co' ></option>
<option value = '​ Komoren--km' ></option>
<option value = '​ Kongo--cg' ></option>
<option value = '​ Kongo, Demokratische Republik--cd' ></option>
<option value = '​ Kroatien--hr' ></option>
<option value = '​ Kuba--cu' ></option>
<option value = '​ Kuwait--kw' ></option>
<option value = '​ Laos--la' ></option>
<option value = '​ Lesotho--ls' ></option>
<option value = '​ Lettland--lv' ></option>
<option value = '​ Libanon--lb' ></option>
<option value = '​ Liberia--lr' ></option>
<option value = '​ Libyen--ly' ></option>
<option value = '​ Liechtenstein--li' ></option>
<option value = '​ Litauen--lt' ></option>
<option value = '​ Luxemburg--lu' ></option>
<option value = '​ Montenegro--me' ></option>
<option value = '​ Saint Martin--mf' ></option>
<option value = '​ Macao--mo' ></option>
<option value = '​ Madagaskar--mg' ></option>
<option value = '​ Malawi--mw' ></option>
<option value = '​ Malaysia--my' ></option>
<option value = '​ Malediven--mv' ></option>
<option value = '​ Mali--ml' ></option>
<option value = '​ Malta--mt' ></option>
<option value = '​ Marianen--mp' ></option>
<option value = '​ Marokko--ma' ></option>
<option value = '​ Marshall Inseln--mh' ></option>
<option value = '​ Martinique--mq' ></option>
<option value = '​ Mauretanien--mr' ></option>
<option value = '​ Mauritius--mu' ></option>
<option value = '​ Mayotte--yt' ></option>
<option value = '​ Mazedonien--mk' ></option>
<option value = '​ Mexiko--mx' ></option>
<option value = '​ Mikronesien--fm' ></option>
<option value = '​ Mocambique--mz' ></option>
<option value = '​ Moldavien--md' ></option>
<option value = '​ Monaco--mc' ></option>
<option value = '​ Mongolei--mn' ></option>
<option value = '​ Montserrat--ms' ></option>
<option value = '​ Namibia--na' ></option>
<option value = '​ Nauru--nr' ></option>
<option value = '​ Nepal--np' ></option>
<option value = '​ Neukaledonien--nc' ></option>
<option value = '​ Neuseeland--nz' ></option>
<option value = '​ Nicaragua--ni' ></option>
<option value = '​ Niederlande--nl' ></option>
<option value = ' Niederländische Antillen--an' ></option>
<option value = ' Niger--ne' ></option>
<option value = ' Nigeria--ng' ></option>
<option value = ' Niue--nu' ></option>
<option value = ' Nord Korea--kp' ></option>
<option value = ' Norfolk Inseln--nf' ></option>
<option value = ' Norwegen--no' ></option>
<option value = ' Oman--om' ></option>
<option value = ' Österreich--at' ></option>
<option value = ' Pakistan--pk' ></option>
<option value = ' Palästina--ps' ></option>
<option value = ' Palau--pw' ></option>
<option value = ' Panama--pa' ></option>
<option value = ' Papua Neuguinea--pg' ></option>
<option value = ' Paraguay--py' ></option>
<option value = ' Peru--pe' ></option>
<option value = ' Philippinen--ph' ></option>
<option value = ' Pitcairn--pn' ></option>
<option value = ' Polen--pl' ></option>
<option value = ' Portugal--pt' ></option>
<option value = ' Puerto Rico--pr' ></option>
<option value = ' Qatar--qa' ></option>
<option value = ' Reunion--re' ></option>
<option value = ' Ruanda--rw' ></option>
<option value = ' Rumänien--ro' ></option>
<option value = ' Rußland--ru' ></option>
<option value = ' Serbien--rs' ></option>
<option value = ' Saint Lucia--lc' ></option>
<option value = ' Sambia--zm' ></option>
<option value = ' Samoa--as' ></option>
<option value = ' Samoa--ws' ></option>
<option value = ' San Marino--sm' ></option>
<option value = ' Sao Tome--st' ></option>
<option value = ' Saudi Arabien--sa' ></option>
<option value = ' Schweden--se' ></option>
<option value = ' Schweiz--ch' ></option>
<option value = ' Senegal--sn' ></option>
<option value = ' Seychellen--sc' ></option>
<option value = ' Sierra Leone--sl' ></option>
<option value = ' Singapur--sg' ></option>
<option value = ' Slowakei--sk' ></option>
<option value = ' Slowenien--si' ></option>
<option value = ' Solomon Inseln--sb' ></option>
<option value = ' Somalia--so' ></option>
<option value = ' South Georgia, South Sandwich Isl.--gs' ></option>
<option value = ' Spanien--es' ></option>
<option value = ' Sri Lanka--lk' ></option>
<option value = ' St. Helena--sh' ></option>
<option value = ' St. Kitts Nevis Anguilla--kn' ></option>
<option value = ' St. Pierre und Miquelon--pm' ></option>
<option value = ' St. Vincent--vc' ></option>
<option value = ' Süd Korea--kr' ></option>
<option value = ' Südafrika--za' ></option>
<option value = ' Sudan--sd' ></option>
<option value = ' Surinam--sr' ></option>
<option value = ' Svalbard und Jan Mayen Islands--sj' ></option>
<option value = ' Swasiland--sz' ></option>
<option value = ' Syrien--sy' ></option>
<option value = ' Tadschikistan--tj' ></option>
<option value = ' East Timor--tl' ></option>
<option value = ' Taiwan--tw' ></option>
<option value = ' Tansania--tz' ></option>
<option value = ' Thailand--th' ></option>
<option value = ' Timor--tp' ></option>
<option value = ' Togo--tg' ></option>
<option value = ' Tokelau--tk' ></option>
<option value = ' Tonga--to' ></option>
<option value = ' Trinidad Tobago--tt' ></option>
<option value = ' Tschad--td' ></option>
<option value = ' Tschechische Republik--cz' ></option>
<option value = ' Tunesien--tn' ></option>
<option value = ' Türkei--tr' ></option>
<option value = ' Turkmenistan--tm' ></option>
<option value = ' Turks und Kaikos Inseln--tc' ></option>
<option value = ' South Sudan--ss' ></option>
<option value = ' Sint Maarten--sx' ></option>
<option value = ' Kosovo--xk' ></option>
<option value = ' Curacao--cw' ></option>
<option value = ' Tuvalu--tv' ></option>
<option value = ' Uganda--ug' ></option>
<option value = ' Ukraine--ua' ></option>
<option value = ' Ungarn--hu' ></option>
<option value = ' Uruguay--uy' ></option>
<option value = ' USA--us' ></option>
<option value = ' Usbekistan--uz' ></option>
<option value = ' Vanuatu--vu' ></option>
<option value = ' Vatikan--va' ></option>
<option value = ' Venezuela--ve' ></option>
<option value = ' Vereinigte Arabische Emirate--ae' ></option>
<option value = ' Vietnam--vn' ></option>
<option value = ' Virgin Island (Brit.)--vg' ></option>
<option value = ' Virgin Island (USA)--vi' ></option>
<option value = ' Wallis et Futuna--wf' ></option>
<option value = ' Weissrussland--by' ></option>
<option value = ' Westsahara--eh' ></option>
<option value = ' Zentralafrikanische Republik--cf' ></option>
<option value = ' Zimbabwe--zw' ></option>
<option value = ' Zypern--cy' ></option>`